travis:
  secure:
    BINSTAR_TOKEN: eRej1PaiYn9LSCCp8NoFmqNze+CUeqomTDUpF+QLGA47wjTOm2yXtygPi68LcARj4GB4qM+qQUuPoV01Q65tKST3SrVBGM3PpEzgnRumZQuNn77mfrWI5XLIM58+94Enrc4l5IOQpak+Q1hReB+n6OM4wPjy9ZmcoDVNw6Qkk5TRteznir4712OB3kLatCp1fZQH2M8namXDQgExE7EjgJg3bu7X9rM9vdr3Ek2TwDpQGuU6DKtt/CjuCT6AIONp/b9YWxLFOLrbXB/4PX/OWApJdsnzfYEo8JlrsHWx9DK6h60lmUdP/p8vpwnpCqASOi+opJsnT48ktGUL2wGKHAyStuYCypq+Job+bJhZhazh7/zqba7OTiahFFx/lHsoPh0kSajByfBhh1C/rnu5ow7DYPnw+cAgvw3sATko1NW9+u5Nr/8ub7dbvLCW660xZ/5DijyfYnTexGlNYLJlfTn0lwMCkAiblhaIjVbT80kLWU5GUQzaDemx6b7J71MSB4T/pRsp/I53H2P79HMPLMfZLopp4T2EQDhoswugL6SJApFhZsIu76Hl/nEbH+f4NbRQf0t07ucK93Xoc4p1ujoq0i05w+yGcYyoOudZqJjvqf7WIxAbEmhEmgtekGmHwwEKbFt/pr5odmz7JrSP2JIIooCivttbHWQuQqjZyrk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
